language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3

before_install:
  - gem uninstall -a bundler
  - gem install bundler -v '1.6.6'

script: bundle exec rake build

notifications:
  email:
    on_success: never
    on_failure: never
